---
- hosts: clusternodes
  become: yes
  become_method: sudo
  serial: 4

  tasks: 
    - name: Ensure vim is present
      apt: name=vim state=installed

    - name: Ensure alias vi is vim
      lineinfile:
        dest=/home/pi/.bashrc
        line="alias vi='vim'"
        regexp="^alias vi='vim'"
        owner=pi
        state=present
        insertafter="^# some more ls aliases"
        create=True

    - name: Ensure docker jessie prerequisites present
      apt: name={{ item }} state=installed
      with_items: 
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common

    - name: Ensure docker GPG key present
      apt_key: url=https://download.docker.com/linux/debian/gpg state=present

    - name: Ensure docker repository present
      apt_repository: repo='deb [arch=armhf] https://download.docker.com/linux/debian jessie stable' state=present filename='docker' update_cache='yes'

    - name: Ensure docker installed
      apt: name=docker-ce state=installed

    - name: Ensure docker service is running
      service: name=docker state=started
