---
- name: Ensure docker jessie prerequisites present
  apt: name={{ item }} state=installed
  with_items: # Loops all the following values and substitutes {{ item }} with them
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg2
  - software-properties-common

- name: Ensure docker GPG key present
  apt_key: url=https://download.docker.com/linux/debian/gpg state=present

- name: Ensure docker repository present
  apt_repository: repo='deb [arch=armhf] https://download.docker.com/linux/debian jessie stable' state=present filename='docker' update_cache='yes'

- name: Ensure docker installed
  apt: name=docker-ce state=installed

- name: Ensure docker.service file is not messy with an incompatible -H fd:// and a hosts in /etc/docker/daemon.json configuration
  template:
    src: templates/docker.service.j2
    dest: /lib/systemd/system/docker.service
  register: dockerSystemConfig

- name: Restart docker when system config change
  systemd:
    state: reloaded
    daemon_reload: yes
    name: docker
  when: dockerSystemConfig.changed

- name: Ensure docker service is running
  service: name=docker state=started

- name: Change docker configuration and restart
  template:
    src: templates/daemon.json.j2
    dest: /etc/docker/daemon.json
  register: dockerConfig

- name: Restart docker when config change
  service: name=docker state=restarted
  when: dockerConfig.changed

# Initialize the swarm nodes
- include: swarm_cluster.yaml
